```{r}
rm(list=ls()) 
library(tidyverse)
library(ggthemes)
library(openxlsx)
library(ggpubr)
library(readxl)
```

```{r}
url <- "https://github.com/Sandermdale/SOK-1004-Eksamen/blob/main/totale%20l%C3%A5n.xlsx?raw=true"
df_loan <- url %>%  
  read.xlsx() %>% 
  as_tibble() 
```

```{r}
df_loan <- df_loan %>% 
  mutate(År=as.numeric(År)) %>%
  rename(Antall_lån=`Total.loans`)
df_loan <- df_loan[-c(0:81, 113:196), ]
```

```{r}
df_loan %>%
  ggplot(aes(År, y=Antall_lån))+
  geom_line()+
  scale_y_continuous(labels = scales::comma)+
  theme_bw()
```

```{r}
url <- "https://github.com/Sandermdale/SOK-1004-Eksamen/blob/main/Konkurs%201920%20(eksamen-1004).xlsx?raw=true"
df_konkurser <- url %>%  
  read.xlsx() %>% 
  as_tibble() 
```

```{r}
df_konkurser <- df_konkurser %>% 
  rename(Antall_konkurser =`Number.of.bankruptcies.(from.1887)`) %>% 
  mutate(Year=as.numeric(Year)) %>% 
  rename(År=Year)
df_konkurser <- df_konkurser[-c(0:12, 45:74), ]
```

```{r}
#endrer antall_konkurs til årlig prosentvis endring
df_konkurs <- df_konkurser %>% 
  mutate(lag_konkurs=lag(Antall_konkurser,1)) %>%
  mutate(Årlig_prosentvis_endring=100*(Antall_konkurser-lag_konkurs)/Antall_konkurser)
df_konkurser <- df_konkurser[-c(0:1), ]

```

```{r}
df_konkurser %>%
  ggplot(aes(År, y=Antall_konkurser))+
  geom_line(color="red")+
  theme_bw()
```

```{r}
url <- "https://github.com/Sandermdale/SOK-1004-Eksamen/blob/main/Realrente.xlsx?raw=true"
df_realrente <- url %>%  
  read.xlsx() %>% 
  as_tibble() 
```

```{r}
df_realrente <- df_realrente %>% 
  rename(årlig_vekt_kpi=`Årlig.vekst.i.KPI`) %>% 
  rename(Nominell_rente=`Nominell.rente`)
df_realrente <- df_realrente[-c(0:64,96:164), ]
```

```{r}
df_konkurser <- cbind(df_realrente$Realrente, df_konkurser)
df_konkurser <- df_konkurser %>% 
  mutate(realrenten=`df_realrente$Realrente`)
```

```{r}
url <- "https://github.com/Sandermdale/SOK-1004-Eksamen/blob/main/Pengemengde.xlsx?raw=true"
  
df_pengemengde <- url %>%  
  read.xlsx() %>% 
  as_tibble
df_pengemengde <- df_pengemengde %>% 
  rename(M0_mill_kr=`M0(Mill)`) %>% 
  rename(M2_mill_kr=`M2.(Mill)`)
```

```{r}
df_pengemengde %>% 
  ggplot(aes(x=År, y=M0_mill_kr))+
  geom_line(aes(x=År, y=M0_mill_kr), color="blue")+
  theme_bw()
```

```{r}
url <- "https://github.com/Sandermdale/SOK-1004-Eksamen/blob/main/KPI,Rente%20og%20Inlfasjon.xlsx?raw=true"
  
df_inflasjon_kpi <- url %>%  
  read.xlsx() %>% 
  as_tibble()
```

```{r}
df_inflasjon_kpi <- df_inflasjon_kpi[-c (1:81),] 
df_inflasjon_kpi <- df_inflasjon_kpi[-(32:118),]
df_inflasjon_kpi[is.na(df_inflasjon_kpi)] = 0 
df_inflasjon_kpi <- df_inflasjon_kpi %>% 
  rename(År=Year) %>% 
  mutate(År=as.numeric(År)) %>% 
  rename(inflasjon=`Inflation.rate`)
```

```{r}
ggplot(data=df_realrente, aes(x=År, y=Realrente))+
  geom_line(data=df_inflasjon_kpi, aes(x=År, y=inflasjon), color="blue")+
  geom_line(data=df_realrente, aes(x=År, y=Realrente), color="red")+
  geom_line(data=df_realrente, aes(x=År, y=Nominell_rente))+
  theme_bw()
```

```{r}
df_realrente %>% 
  ggplot(aes(x=År, y=Nominell_rente))+
  geom_line()+
  theme_bw()
```
